name: samuelgreggmusic
favicon: null
layout_spectrum: 0.94455
typography_spectrum: 0.84159
title: Samuel Gregg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5d4cc'
    - '#465460'
    - '#d92854'
    - '#839096'
    - '#da739a'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
