name: samuelgreggmusic
favicon: null
layout_spectrum: 0.4284183077979833
typography_spectrum: 0.43298209737986326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7462655771523714
  lightness: 0.5588746147695929
  saturation: 0.4104983333963901
  rhythmicContrast: 0.07510396698489785
purpose: []
