name: samuelgreggmusic
favicon: null
layout_spectrum: 0.94455
typography_spectrum: 0.43298209737986326
title: Samuel Gregg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5d4cc'
    - '#465460'
    - '#d92854'
    - '#839096'
    - '#da739a'
  brandStrength: 0.7462655771523714
  lightness: 0.625
  saturation: 0.4104983333963901
  rhythmicContrast: 0.07510396698489785
purpose: []
