name: samuelgreggmusic
favicon: null
layout_spectrum: 0.4284183077979833
typography_spectrum: 0.43298209737986326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee4e0'
    - '#455660'
    - '#da2956'
    - '#8d989c'
    - '#dc6f89'
  brandStrength: 0.7462655771523714
  lightness: 0.625
  saturation: 0.4104983333963901
  rhythmicContrast: 0.07510396698489785
purpose: []
