name: samuelgreggmusic.com
favicon: null
layout_spectrum: 0.07456
typography_spectrum: 0.84159
title: SamuelGreggMusic.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6d4ca'
    - '#455660'
    - '#68767c'
    - '#879397'
    - '#aeb8b8'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
